server:
  port: 4100

spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        watch:
          enabled: true
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}


